#!/bin/zsh

(( cols=$(tput cols) ))
(( halfcols=cols/2 ))

function wrap() { fold -s -w $halfcols "$1" }

function prepend() { echo "$1"; cat "$2" }

function columnate() {
   pr -w $cols -m -T <(prepend 'Original' <(wrap "$1")) <(prepend 'Result' <(wrap "$2"))
}

columnate "$1" "$2"
